<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept</name>
   <tag></tag>
   <elementGuidId>9fe3a01d-f674-465d-9440-e5dc880f087e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cookie-btn > button:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='acceptCookie();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdb44545-52bd-4044-8388-a88a8616ea88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>acceptCookie();</value>
      <webElementGuid>5ef9dd76-0c52-4ba6-be6b-977b4238e6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      Accept
                  </value>
      <webElementGuid>bdee1d81-a8a6-4704-b05b-fa9f8da089eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookie-notice&quot;)/div[@class=&quot;light display-right&quot;]/div[@class=&quot;cookie-content&quot;]/div[@class=&quot;cookie-msg&quot;]/div[@class=&quot;cookie-btn&quot;]/button[2]</value>
      <webElementGuid>fc58d725-fdd1-42ec-8c7c-c45602eca8ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='acceptCookie();']</value>
      <webElementGuid>ca913d9d-7b20-495f-984a-cf4de3a13f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookie-notice']/div/div[3]/div/div[2]/button[2]</value>
      <webElementGuid>3844d9f9-bd74-4640-b6f3-fe413da957d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/following::button[1]</value>
      <webElementGuid>7c7c304c-633f-405f-bfd1-572ca4eb63fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::button[2]</value>
      <webElementGuid>3f898a60-9f28-47bc-9f97-76bbe79b8519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>1d4a5361-7f70-4b1d-825f-8d1665446588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>7d4cbb52-e0e7-4877-aa1a-eefd7a02cb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                      Accept
                  ' or . = '
                      Accept
                  ')]</value>
      <webElementGuid>7e24b5b2-9bba-4b3b-8fbd-a71803eddf04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
