<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_button</name>
   <tag></tag>
   <elementGuidId>073d23b4-5cd4-46b3-8045-159b04dafc89</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;ic-close-notice-white&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='ic-close-notice-white']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/images/icons/ic-close-notice-white.png' and @alt = 'ic-close-notice-white']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5bc00001-d828-4262-9dfd-abfc37cc91f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/icons/ic-close-notice-white.png</value>
      <webElementGuid>aece88b5-3398-488a-8c38-5ae9997441f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ic-close-notice-white</value>
      <webElementGuid>331fcbad-2837-4f50-a177-bb9e233ee79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;focus-outline-hidden&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade ek-schedule-post-modal modal show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/button[@class=&quot;btn-close-modal&quot;]/img[1]</value>
      <webElementGuid>a2651e7d-bd5c-41e5-9356-7b36510ebf72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ic-close-notice-white']</value>
      <webElementGuid>2cb44d6c-1fef-409a-a261-a7699cadcb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/button/img</value>
      <webElementGuid>d0b2ab3a-c30c-40a1-857f-19cccea3c299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/icons/ic-close-notice-white.png' and @alt = 'ic-close-notice-white']</value>
      <webElementGuid>72abc757-3682-4e25-bb21-8cb9fc73418d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
