<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DashboardHeader</name>
   <tag></tag>
   <elementGuidId>7f0c33bf-c35a-4a2e-8e10-dc4633be868d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header.ek-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>2b8bbe81-0f7a-4c20-8304-fbd45da6fdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ek-header</value>
      <webElementGuid>5c11f538-5485-41a6-bc61-00e806d4d9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>☰CreateAI EditBetaEditMontageGo PremiumSaved ClipSaved ClipsConnect StatusConnection StatusConnect NowConnect NowConnect NowConnect NowConnect NowConnect NowConnect Now2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we'll turn your best moments into highlights!4 hours agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogoutAI EditBetaEditMontageGo Premium2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we'll turn your best moments into highlights!4 hours agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogout</value>
      <webElementGuid>7839163c-560c-4920-a47a-a7418d7822c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/header[@class=&quot;ek-header&quot;]</value>
      <webElementGuid>0e324c58-7227-4e25-9263-b7bc5a44e1c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/header</value>
      <webElementGuid>65e52543-579f-46d7-a483-368b015e9a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Japanese'])[1]/following::header[1]</value>
      <webElementGuid>957ba27b-9bc0-46d4-a634-ef42f0ab9ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='French'])[1]/following::header[1]</value>
      <webElementGuid>cbb30992-45a5-4302-b1a9-9cc21bb3fb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>33707861-80a7-4e84-9c96-c66682a21a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = concat(&quot;☰CreateAI EditBetaEditMontageGo PremiumSaved ClipSaved ClipsConnect StatusConnection StatusConnect NowConnect NowConnect NowConnect NowConnect NowConnect NowConnect Now2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we&quot; , &quot;'&quot; , &quot;ll turn your best moments into highlights!4 hours agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogoutAI EditBetaEditMontageGo Premium2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we&quot; , &quot;'&quot; , &quot;ll turn your best moments into highlights!4 hours agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogout&quot;) or . = concat(&quot;☰CreateAI EditBetaEditMontageGo PremiumSaved ClipSaved ClipsConnect StatusConnection StatusConnect NowConnect NowConnect NowConnect NowConnect NowConnect NowConnect Now2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we&quot; , &quot;'&quot; , &quot;ll turn your best moments into highlights!4 hours agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogoutAI EditBetaEditMontageGo Premium2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we&quot; , &quot;'&quot; , &quot;ll turn your best moments into highlights!4 hours agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogout&quot;))]</value>
      <webElementGuid>5709b819-e14d-4f74-8d5c-6c86cfd0ec98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
