<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Eklipse_Dashboard</name>
   <tag></tag>
   <elementGuidId>dd322ab5-a637-4832-be6b-92c29da0e138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ek-dashboard__home.ek-content-bar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5cba5b7e-f04a-4434-b4b6-4f1101b17c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ek-dashboard__home ek-content-bar </value>
      <webElementGuid>bef06957-8f0d-4390-8ae4-d4446d431052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-recent-on-screen34010788_19</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>a299c353-9c1e-45a7-b399-a9c0eccc8139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen34010788_19</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>b1385766-87ca-422e-b6b7-5c817a9348f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time34010788_19</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b7915823-c2eb-4c27-b6aa-fceee39bd9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired34010788_19</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>889444fa-26a1-435d-9c06-fca2ae7503a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Import StreamsAdd new Twitch, Tiktok, YT or Kick!AI Edit BetaEdit your clips using AI!Convert to VerticalTurn your videos into TikTok formatSharePost and Schedule your clipsPrivate StreamGame and clip privatelyDidn’t see your stream?RefreshGenerate Stream HighlightsTry with your VOD link: 3 trial availableImportSelect...Connect for the Ultimate ExperienceFind your vods right after you're done streamingGet instant highlights with auto-processingORGenerate from External SourceEnter a stream URLUpload TikTok LiveUpload from local files</value>
      <webElementGuid>4a6a947f-f232-4318-8732-7bd353a2f0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard p-0&quot;]/div[@class=&quot;ek-widget-wrapper d-flex&quot;]/div[@class=&quot;ek-dashboard__home ek-content-bar&quot;]</value>
      <webElementGuid>086108a9-c96b-42ec-9d6e-65852a9420e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/div</value>
      <webElementGuid>31cbca51-9864-4452-a217-a38f2372243d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[3]/following::div[3]</value>
      <webElementGuid>4297db09-aeeb-4775-aa1a-0a1b60f22222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[3]/following::div[4]</value>
      <webElementGuid>c5a9c533-d487-431c-90fa-303994f3ddf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div</value>
      <webElementGuid>d8d0b03f-2931-45aa-80b7-68ec3a7ec243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Import StreamsAdd new Twitch, Tiktok, YT or Kick!AI Edit BetaEdit your clips using AI!Convert to VerticalTurn your videos into TikTok formatSharePost and Schedule your clipsPrivate StreamGame and clip privatelyDidn’t see your stream?RefreshGenerate Stream HighlightsTry with your VOD link: 3 trial availableImportSelect...Connect for the Ultimate ExperienceFind your vods right after you&quot; , &quot;'&quot; , &quot;re done streamingGet instant highlights with auto-processingORGenerate from External SourceEnter a stream URLUpload TikTok LiveUpload from local files&quot;) or . = concat(&quot;Import StreamsAdd new Twitch, Tiktok, YT or Kick!AI Edit BetaEdit your clips using AI!Convert to VerticalTurn your videos into TikTok formatSharePost and Schedule your clipsPrivate StreamGame and clip privatelyDidn’t see your stream?RefreshGenerate Stream HighlightsTry with your VOD link: 3 trial availableImportSelect...Connect for the Ultimate ExperienceFind your vods right after you&quot; , &quot;'&quot; , &quot;re done streamingGet instant highlights with auto-processingORGenerate from External SourceEnter a stream URLUpload TikTok LiveUpload from local files&quot;))]</value>
      <webElementGuid>32e00601-1be2-494c-8823-afda4c1b3786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
