<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_nav</name>
   <tag></tag>
   <elementGuidId>787614be-e967-4d3f-a8e0-f7ea976308cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.navbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mySidebar']/div[2]/nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>ed7c0a40-cc48-44a2-a966-b6fcb0b78b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar</value>
      <webElementGuid>e6fbef92-5b99-4dbe-a902-e05dd4def6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Free MemberUpgrade to Premium Plan have more benefits and moreUpgradedafashafi@gmail.com  ·  0 AccessPersonal AccountCreate a CollaborationUpgrade to TeamsHomeClip LibraryStream/VideoTwitch/Kick ClipsPlaylistVoice CommandNewEditsAI EditNewEdited ClipsMontagesContent PublisherTime-saving ToolsTiktok BackupPrivate StreamPro EditsAutomationConnect StreamLanguageAccount SettingsHelpLogout</value>
      <webElementGuid>a613ae4c-7e08-455c-8ba2-fa4563e31f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mySidebar&quot;)/div[@class=&quot;menu-box-content&quot;]/nav[@class=&quot;navbar&quot;]</value>
      <webElementGuid>fd47e5dd-4144-4f7f-924f-b50dd7c2fd12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mySidebar']/div[2]/nav</value>
      <webElementGuid>dd672382-09ab-4dd5-8801-c2c38f23d29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav</value>
      <webElementGuid>a6acf33a-ff71-4a9f-b2ae-8df4fd980b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'Free MemberUpgrade to Premium Plan have more benefits and moreUpgradedafashafi@gmail.com  ·  0 AccessPersonal AccountCreate a CollaborationUpgrade to TeamsHomeClip LibraryStream/VideoTwitch/Kick ClipsPlaylistVoice CommandNewEditsAI EditNewEdited ClipsMontagesContent PublisherTime-saving ToolsTiktok BackupPrivate StreamPro EditsAutomationConnect StreamLanguageAccount SettingsHelpLogout' or . = 'Free MemberUpgrade to Premium Plan have more benefits and moreUpgradedafashafi@gmail.com  ·  0 AccessPersonal AccountCreate a CollaborationUpgrade to TeamsHomeClip LibraryStream/VideoTwitch/Kick ClipsPlaylistVoice CommandNewEditsAI EditNewEdited ClipsMontagesContent PublisherTime-saving ToolsTiktok BackupPrivate StreamPro EditsAutomationConnect StreamLanguageAccount SettingsHelpLogout')]</value>
      <webElementGuid>99e0996b-9704-4dd5-82ad-f90348ca1ba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
