<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VideoList</name>
   <tag></tag>
   <elementGuidId>a97d3f61-c923-4c0e-9fa7-d7e31150945a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.display-card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-0-0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13d634eb-e83d-450d-ba70-6db3f03250db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>display-card</value>
      <webElementGuid>5c8865ff-ad4a-4067-8401-25bf8a4ba119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>02:55:153 days agoFortnitesolo reload | !add !twitter | 6/30</value>
      <webElementGuid>6e1c5427-8b4a-4ee3-9754-d3c151bad6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-0-0&quot;)/div[@class=&quot;display-card&quot;]</value>
      <webElementGuid>88868509-2255-400d-a3ad-e08af1544031</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-0-0']/div</value>
      <webElementGuid>c6aaa49b-44fa-4231-aeaa-cb789b00d825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.twitch.tv/videos/2455055280'])[1]/following::div[12]</value>
      <webElementGuid>7ad21126-a8c2-4aea-b783-563724ba5846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='malding at valorant day 956'])[1]/preceding::div[33]</value>
      <webElementGuid>528697dd-7a90-41a9-b141-29b596b6b432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>0d0717f1-0bb2-4b17-a754-736841df05d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '02:55:153 days agoFortnitesolo reload | !add !twitter | 6/30' or . = '02:55:153 days agoFortnitesolo reload | !add !twitter | 6/30')]</value>
      <webElementGuid>1e7be4b0-c900-46dc-87aa-81a6d4d6715a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
