<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccountSetting_Dashboard</name>
   <tag></tag>
   <elementGuidId>adf910b9-e055-431a-9275-4d4b341b0a41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ek-account-setting</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ea00d12-570b-41b9-926d-1dff8fdd88f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ek-account-setting</value>
      <webElementGuid>984b452a-5e13-4eb7-a56a-b3534c57ad14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account SettingPersonal DetailsPlugin SettingGame SettingNewConnect Rumble to Eklipse now!Connected AccountTwitchConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectYoutubeConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectFacebookConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectKickConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectRumbleConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectAdd More Socials To Your ProfileYou're almost all set! Just link your socials to Eklipse for easy sharing and updates on analytics and services!TikTokConnect your account to allow direct share to TikTokConnectDiscord SettingsConnect Discord to receive notifications and add your server to auto-sharingDiscord AccountConnect your account to receive live updates via DiscordConnectEklipse BotConnect a Discord Server to auto-share your latest posts with your communityAdd to ServerProfile settingsNameEmailSave ChangesPasswordPasswordChange PasswordAccount RemovalDelete your account means you can't recover it at any time after taking this actionDelete AccountCurrent passwordNew passwordConfirm passwordSave ChangesLet your clips being played on your Twitch Stream!Now you can add your clips to your live stream whenever you are on away from keyboard or start stream, Just follow several instructions below:Add clips you like to the playlistChoose Playlist you want to be shown on your BRB or Starting ScreenCopy URL to your sceneDo not stretch the layer will causing the Eklipse can't detect the screen properlyLearn MoreVideo Player is loading.Play VideoPlayUnmuteCurrent Time 0:00/Duration 0:56Loaded: 7.32%0:00Stream Type LIVESeek to live, currently behind liveLIVERemaining Time -0:56 1xPlayback RateChaptersChaptersDescriptionsdescriptions off, selectedCaptionscaptions settings, opens captions settings dialogcaptions off, selectedAudio TrackPicture-in-PictureFullscreenThis is a modal window.Beginning of dialog window. Escape will cancel and close the window.TextColorWhiteBlackRedGreenBlueYellowMagentaCyanTransparencyOpaqueSemi-TransparentBackgroundColorBlackWhiteRedGreenBlueYellowMagentaCyanTransparencyOpaqueSemi-TransparentTransparentWindowColorBlackWhiteRedGreenBlueYellowMagentaCyanTransparencyTransparentSemi-TransparentOpaqueFont Size50%75%100%125%150%175%200%300%400%Text Edge StyleNoneRaisedDepressedUniformDropshadowFont FamilyProportional Sans-SerifMonospace Sans-SerifProportional SerifMonospace SerifCasualScriptSmall CapsReset restore all settings to the default valuesDoneClose Modal DialogEnd of dialog window.*Currently works for Call of Duty: Modern Warfare 2 &amp; Warzone 2, Apex Legends, Overwatch and Valorant gaming streamsBe Right BackStarting SoonBe Right Back URLCopy URL of your Be Right Back screen to your OBSCopy URLSelect PlaylistChoose available playlist to be played on your Be Right Back ScreenPlaylist Name*We only show playlist which is not emptyEnable Shuffle modeWhen enabled, Eklipse will automatically shuffle all the videos on your playlistStarting Soon URLCopy URL of your Starting Soon screen to your OBSCopy URLSelect PlaylistChoose available playlist to be played on your Starting Soon ScreenPlaylist Name*We only show playlist which is not emptyEnable Shuffle modeWhen enabled, Eklipse will automatically shuffle all the videos on your playlistLeague of LegendValorantGamer NameFill in with your Player nameRegionChoose the region of your countrySelect regionBrazilEurope Nordic &amp; EastEurope WestJapanKoreanLANLASNorth AmericanOceaniaPhilippinesRussiaSingaporeThailandTurkiyeTaiwanVietnamSaveGamer NameFill in with your Player nameTagFill in with your taglineRegionChoose the region of your countrySelect regionBrazilEurope Nordic &amp; EastEurope WestJapanKoreanLANLASNorth AmericanOceaniaPhilippinesRussiaSingaporeThailandTurkiyeTaiwanVietnamSave</value>
      <webElementGuid>43614185-1343-4452-b0fc-5a1c9813500c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-account-setting&quot;]</value>
      <webElementGuid>e64e3dce-569a-45dd-8988-a0c02f53181f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div</value>
      <webElementGuid>e6e87fa1-f384-4b01-a044-a292c074cc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[3]/following::div[2]</value>
      <webElementGuid>e01ef1e4-3240-491d-85e0-c685737d9e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[3]/following::div[3]</value>
      <webElementGuid>caa971f8-12f8-44ed-b3da-a3bdab5157dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>f4c06b0e-6500-4b06-aa99-6601f52cb251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Account SettingPersonal DetailsPlugin SettingGame SettingNewConnect Rumble to Eklipse now!Connected AccountTwitchConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectYoutubeConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectFacebookConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectKickConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectRumbleConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectAdd More Socials To Your ProfileYou&quot; , &quot;'&quot; , &quot;re almost all set! Just link your socials to Eklipse for easy sharing and updates on analytics and services!TikTokConnect your account to allow direct share to TikTokConnectDiscord SettingsConnect Discord to receive notifications and add your server to auto-sharingDiscord AccountConnect your account to receive live updates via DiscordConnectEklipse BotConnect a Discord Server to auto-share your latest posts with your communityAdd to ServerProfile settingsNameEmailSave ChangesPasswordPasswordChange PasswordAccount RemovalDelete your account means you can&quot; , &quot;'&quot; , &quot;t recover it at any time after taking this actionDelete AccountCurrent passwordNew passwordConfirm passwordSave ChangesLet your clips being played on your Twitch Stream!Now you can add your clips to your live stream whenever you are on away from keyboard or start stream, Just follow several instructions below:Add clips you like to the playlistChoose Playlist you want to be shown on your BRB or Starting ScreenCopy URL to your sceneDo not stretch the layer will causing the Eklipse can&quot; , &quot;'&quot; , &quot;t detect the screen properlyLearn MoreVideo Player is loading.Play VideoPlayUnmuteCurrent Time 0:00/Duration 0:56Loaded: 7.32%0:00Stream Type LIVESeek to live, currently behind liveLIVERemaining Time -0:56 1xPlayback RateChaptersChaptersDescriptionsdescriptions off, selectedCaptionscaptions settings, opens captions settings dialogcaptions off, selectedAudio TrackPicture-in-PictureFullscreenThis is a modal window.Beginning of dialog window. Escape will cancel and close the window.TextColorWhiteBlackRedGreenBlueYellowMagentaCyanTransparencyOpaqueSemi-TransparentBackgroundColorBlackWhiteRedGreenBlueYellowMagentaCyanTransparencyOpaqueSemi-TransparentTransparentWindowColorBlackWhiteRedGreenBlueYellowMagentaCyanTransparencyTransparentSemi-TransparentOpaqueFont Size50%75%100%125%150%175%200%300%400%Text Edge StyleNoneRaisedDepressedUniformDropshadowFont FamilyProportional Sans-SerifMonospace Sans-SerifProportional SerifMonospace SerifCasualScriptSmall CapsReset restore all settings to the default valuesDoneClose Modal DialogEnd of dialog window.*Currently works for Call of Duty: Modern Warfare 2 &amp; Warzone 2, Apex Legends, Overwatch and Valorant gaming streamsBe Right BackStarting SoonBe Right Back URLCopy URL of your Be Right Back screen to your OBSCopy URLSelect PlaylistChoose available playlist to be played on your Be Right Back ScreenPlaylist Name*We only show playlist which is not emptyEnable Shuffle modeWhen enabled, Eklipse will automatically shuffle all the videos on your playlistStarting Soon URLCopy URL of your Starting Soon screen to your OBSCopy URLSelect PlaylistChoose available playlist to be played on your Starting Soon ScreenPlaylist Name*We only show playlist which is not emptyEnable Shuffle modeWhen enabled, Eklipse will automatically shuffle all the videos on your playlistLeague of LegendValorantGamer NameFill in with your Player nameRegionChoose the region of your countrySelect regionBrazilEurope Nordic &amp; EastEurope WestJapanKoreanLANLASNorth AmericanOceaniaPhilippinesRussiaSingaporeThailandTurkiyeTaiwanVietnamSaveGamer NameFill in with your Player nameTagFill in with your taglineRegionChoose the region of your countrySelect regionBrazilEurope Nordic &amp; EastEurope WestJapanKoreanLANLASNorth AmericanOceaniaPhilippinesRussiaSingaporeThailandTurkiyeTaiwanVietnamSave&quot;) or . = concat(&quot;Account SettingPersonal DetailsPlugin SettingGame SettingNewConnect Rumble to Eklipse now!Connected AccountTwitchConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectYoutubeConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectFacebookConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectKickConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectRumbleConnect account and enable auto-processing, Eklipse will automatically create clips from your latest streamConnectAdd More Socials To Your ProfileYou&quot; , &quot;'&quot; , &quot;re almost all set! Just link your socials to Eklipse for easy sharing and updates on analytics and services!TikTokConnect your account to allow direct share to TikTokConnectDiscord SettingsConnect Discord to receive notifications and add your server to auto-sharingDiscord AccountConnect your account to receive live updates via DiscordConnectEklipse BotConnect a Discord Server to auto-share your latest posts with your communityAdd to ServerProfile settingsNameEmailSave ChangesPasswordPasswordChange PasswordAccount RemovalDelete your account means you can&quot; , &quot;'&quot; , &quot;t recover it at any time after taking this actionDelete AccountCurrent passwordNew passwordConfirm passwordSave ChangesLet your clips being played on your Twitch Stream!Now you can add your clips to your live stream whenever you are on away from keyboard or start stream, Just follow several instructions below:Add clips you like to the playlistChoose Playlist you want to be shown on your BRB or Starting ScreenCopy URL to your sceneDo not stretch the layer will causing the Eklipse can&quot; , &quot;'&quot; , &quot;t detect the screen properlyLearn MoreVideo Player is loading.Play VideoPlayUnmuteCurrent Time 0:00/Duration 0:56Loaded: 7.32%0:00Stream Type LIVESeek to live, currently behind liveLIVERemaining Time -0:56 1xPlayback RateChaptersChaptersDescriptionsdescriptions off, selectedCaptionscaptions settings, opens captions settings dialogcaptions off, selectedAudio TrackPicture-in-PictureFullscreenThis is a modal window.Beginning of dialog window. Escape will cancel and close the window.TextColorWhiteBlackRedGreenBlueYellowMagentaCyanTransparencyOpaqueSemi-TransparentBackgroundColorBlackWhiteRedGreenBlueYellowMagentaCyanTransparencyOpaqueSemi-TransparentTransparentWindowColorBlackWhiteRedGreenBlueYellowMagentaCyanTransparencyTransparentSemi-TransparentOpaqueFont Size50%75%100%125%150%175%200%300%400%Text Edge StyleNoneRaisedDepressedUniformDropshadowFont FamilyProportional Sans-SerifMonospace Sans-SerifProportional SerifMonospace SerifCasualScriptSmall CapsReset restore all settings to the default valuesDoneClose Modal DialogEnd of dialog window.*Currently works for Call of Duty: Modern Warfare 2 &amp; Warzone 2, Apex Legends, Overwatch and Valorant gaming streamsBe Right BackStarting SoonBe Right Back URLCopy URL of your Be Right Back screen to your OBSCopy URLSelect PlaylistChoose available playlist to be played on your Be Right Back ScreenPlaylist Name*We only show playlist which is not emptyEnable Shuffle modeWhen enabled, Eklipse will automatically shuffle all the videos on your playlistStarting Soon URLCopy URL of your Starting Soon screen to your OBSCopy URLSelect PlaylistChoose available playlist to be played on your Starting Soon ScreenPlaylist Name*We only show playlist which is not emptyEnable Shuffle modeWhen enabled, Eklipse will automatically shuffle all the videos on your playlistLeague of LegendValorantGamer NameFill in with your Player nameRegionChoose the region of your countrySelect regionBrazilEurope Nordic &amp; EastEurope WestJapanKoreanLANLASNorth AmericanOceaniaPhilippinesRussiaSingaporeThailandTurkiyeTaiwanVietnamSaveGamer NameFill in with your Player nameTagFill in with your taglineRegionChoose the region of your countrySelect regionBrazilEurope Nordic &amp; EastEurope WestJapanKoreanLANLASNorth AmericanOceaniaPhilippinesRussiaSingaporeThailandTurkiyeTaiwanVietnamSave&quot;))]</value>
      <webElementGuid>55967fc5-0b76-413d-a37d-2aab5130cf7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
