<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account_Profile</name>
   <tag></tag>
   <elementGuidId>c6236b66-6797-4140-8746-3792cb474df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-menu.dropdown-menu-right.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/header/div/div/ul[5]/li/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a4c0963-0662-42dd-bd4a-8f0a9eecfc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4cbe9517-01be-4976-b6e2-976a20e540c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>1bfe00d2-5e31-4ee9-bdee-90693b0db734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b9c2195-f0a3-48d7-a1a7-1989e58bf573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu dropdown-menu-right show</value>
      <webElementGuid>e88f399f-17ed-4eea-99fd-5657e2d5bc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogout</value>
      <webElementGuid>96da520a-f9be-4623-9906-d76d24bdf2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/header[@class=&quot;ek-header&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;navigation d-flex show-desktop&quot;]/ul[@class=&quot;nav-account nav&quot;]/li[@class=&quot;dropdown show nav-item&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right show&quot;]</value>
      <webElementGuid>d2b4d3b3-0f9a-4c42-9cba-4a44f55c9eeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/header/div/div/ul[5]/li/div</value>
      <webElementGuid>16844e0e-2e83-47c3-a7e2-6e4b986320b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See All'])[1]/following::div[1]</value>
      <webElementGuid>ed3aa369-3e11-4d20-be5c-888f9b0fc1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Important] Connect your stream account now!'])[1]/following::div[5]</value>
      <webElementGuid>ab609e35-0757-48dc-ab83-a0bbc868c8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[5]/li/div</value>
      <webElementGuid>bb493505-0e01-4a1f-b39c-b3314f4d9aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Arczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogout' or . = 'Arczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogout')]</value>
      <webElementGuid>58434e5a-8daa-4cc6-bd0b-730d56cc20ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
