<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GameSetting_Valorant</name>
   <tag></tag>
   <elementGuidId>185c659d-1402-43a1-8733-9893c8b9fee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='0']/p)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b43b9ea6-4f8f-4705-9b39-73051f8f60b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Valorant</value>
      <webElementGuid>6cd7c3c8-4bb5-40d0-8361-b411d389dabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-account-setting&quot;]/div[@class=&quot;sc-dkrFOg bpDwEs&quot;]/div[@class=&quot;ek-game-setting&quot;]/ul[@class=&quot;sc-bcXHqe sZiLj account-setting-header&quot;]/li[@id=&quot;0&quot;]/p[1]</value>
      <webElementGuid>0d5d2e0f-cce5-4f79-a798-009c2e54ffb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//li[@id='0']/p)[3]</value>
      <webElementGuid>9bf929a6-72d1-47d7-a3c2-0502877f7671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When enabled, Eklipse will automatically shuffle all the videos on your playlist'])[2]/following::p[2]</value>
      <webElementGuid>c08dc1f7-2f7c-49d8-b079-b9f33c58f97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Shuffle mode'])[2]/following::p[2]</value>
      <webElementGuid>0fd7d849-5ff0-41d2-b127-de0e9a43ae7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fill in with your Player name'])[1]/preceding::p[2]</value>
      <webElementGuid>914a20be-04d0-4a78-8205-50a999d4b295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose the region of your country'])[1]/preceding::p[3]</value>
      <webElementGuid>8bfb54e7-d7d6-4429-9ba4-47379aff59f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Valorant']/parent::*</value>
      <webElementGuid>5ad36de1-1c41-4d55-aca3-f65681392a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[2]/p</value>
      <webElementGuid>3071e5a9-f3ca-4a1c-adb8-7538bcd217f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Valorant' or . = 'Valorant')]</value>
      <webElementGuid>1b8dade8-d528-48f8-a42d-219b94ea863c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
