<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Game_Setting</name>
   <tag></tag>
   <elementGuidId>5c3942d5-c13e-4998-921c-68b3f4a08408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4 > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='4']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a4eca6f0-ca39-4347-9672-be6c11458c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Game Setting</value>
      <webElementGuid>a28d074f-bb6e-433d-9661-60c6a27beab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4&quot;)/p[1]</value>
      <webElementGuid>68f07a93-825f-448a-85fd-d2cbf22bcce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='4']/p</value>
      <webElementGuid>de56fdde-216d-41fc-a655-f374b18812e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Setting'])[1]/following::p[3]</value>
      <webElementGuid>35f59846-83dc-4025-9017-e0b754ec89cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[3]/following::p[3]</value>
      <webElementGuid>26b6b3e2-d908-4210-a210-9dbb30dc39bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[3]/preceding::p[1]</value>
      <webElementGuid>394c2108-17d6-4969-8e39-57cead7705be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect Rumble to Eklipse now!'])[1]/preceding::p[1]</value>
      <webElementGuid>dc5b33f9-faad-47a0-acaf-8b1417051204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Game Setting']/parent::*</value>
      <webElementGuid>8cfbcd7c-0316-475f-a2a8-95ff0eabd6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/p</value>
      <webElementGuid>ad4359ad-82de-437b-8e5e-3cf5d9b35e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Game Setting' or . = 'Game Setting')]</value>
      <webElementGuid>89964b91-7d51-4268-bf3e-5e09af250baf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
