<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fill in with your tagline_tagline</name>
   <tag></tag>
   <elementGuidId>edfce81d-d0ae-47ad-a866-13de4250a2fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputGameSettingsTag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputGameSettingsTag']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae4c6d6e-e432-4e73-a8f5-d59866060ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 1234</value>
      <webElementGuid>14be89e8-5a02-44b8-9d8d-c5bb349c69f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputGameSettingsTag</value>
      <webElementGuid>f3cab6d1-d77c-458e-b2c0-08849cae8783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tagline</value>
      <webElementGuid>34b21e10-f933-4736-ac7c-e7e16b9d1119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de16d110-f0b2-47ac-8eb9-bd5b464abdec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputGameSettingsTag&quot;)</value>
      <webElementGuid>826fc088-b1bf-409d-a095-ff701c43a4b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputGameSettingsTag']</value>
      <webElementGuid>4e7882af-9899-44ce-ae0e-a23992cb2ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/div[4]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>6d9f9059-4000-4f91-b329-7b6ce8df6802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>322f63d6-f599-4254-8ca1-ca2adec65635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Ex: 1234' and @id = 'inputGameSettingsTag' and @name = 'tagline' and @type = 'text']</value>
      <webElementGuid>3151d2d5-ac72-4188-8178-6e5ba2ad041f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
