<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Plugin_Setting</name>
   <tag></tag>
   <elementGuidId>8f1a8a1b-f58a-4d5c-8a17-15dc89de42ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3 > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='3']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>879cc351-8481-4a79-be6d-fd77645b8920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plugin Setting</value>
      <webElementGuid>f023b078-c4f7-4fa4-9eea-22fc62a2ef94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)/p[1]</value>
      <webElementGuid>f5b693cb-1b93-4f35-aaa0-bbad5e990a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='3']/p</value>
      <webElementGuid>6fcaa87f-9091-42cf-aca3-7be87d7a8a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Setting'])[1]/following::p[2]</value>
      <webElementGuid>8b26fe70-1aa1-4edc-852f-a9db393193fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[3]/following::p[2]</value>
      <webElementGuid>7ab67709-60b3-497b-af6f-4cfe9d8e4029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[3]/preceding::p[2]</value>
      <webElementGuid>e123eacd-0f62-4c1b-8b27-99822d103028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect Rumble to Eklipse now!'])[1]/preceding::p[2]</value>
      <webElementGuid>6b74c632-77aa-424c-8e5a-d1a9f762c0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Plugin Setting']/parent::*</value>
      <webElementGuid>10522caa-868f-48f7-ae25-c83939dda886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/p</value>
      <webElementGuid>70c1b4b2-1b30-4d67-85af-98cca07ef8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Plugin Setting' or . = 'Plugin Setting')]</value>
      <webElementGuid>4945a5e2-8ac5-4cfd-9618-e7021ed7ada9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
