<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Understood</name>
   <tag></tag>
   <elementGuidId>9f493ad0-9c9b-47b3-a55a-8ffa9a7bacbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedEklipse.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorEklipse.MuiButton-root.MuiButton-contained.MuiButton-containedEklipse.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorEklipse.css-1rt7tlg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[70]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>928ecc69-2e5b-4215-8ccd-b4681c8ea607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedEklipse MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorEklipse MuiButton-root MuiButton-contained MuiButton-containedEklipse MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorEklipse css-1rt7tlg</value>
      <webElementGuid>870d81fb-ee2e-49af-9e2f-9d477ed2dcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25289c63-885b-4ded-856e-fa4e256fcce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>782e1e11-4dc4-4b62-b3d4-5e7f7e64f19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Understood</value>
      <webElementGuid>04868b81-86b4-4abb-bbf5-bec045ad18a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root MuiModal-root css-e3a0f3&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthXs MuiDialog-paperFullWidth css-si5qco&quot;]/div[@class=&quot;MuiDialogActions-root MuiDialogActions-spacing css-mem132&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedEklipse MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorEklipse MuiButton-root MuiButton-contained MuiButton-containedEklipse MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorEklipse css-1rt7tlg&quot;]</value>
      <webElementGuid>65536dd2-195e-4d0e-9ae5-850c5a30ac99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[70]</value>
      <webElementGuid>4c3eed4d-dd63-4089-9ce2-1519f36cfaa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Clip Found'])[1]/following::button[1]</value>
      <webElementGuid>f29ec7d8-553a-494b-a684-dd10bf68f6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Twitch'])[1]/following::button[1]</value>
      <webElementGuid>68e4509e-c8f3-48bb-84b6-07d17055b292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Understood']/parent::*</value>
      <webElementGuid>a566d4d5-a658-4e3a-9b97-87a5b276c7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button</value>
      <webElementGuid>e96cb284-9983-4f3c-8fd8-1a379ba1fac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Understood' or . = 'Understood')]</value>
      <webElementGuid>68020c33-773d-4a80-9174-f1b3033d910f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
