<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get Clip</name>
   <tag></tag>
   <elementGuidId>0adccf4f-bcee-4d84-992b-f901e4cdc8dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-ar65o0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div[2]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e1b60f0-82c2-4f00-b7f8-4ae3b9954964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-ar65o0</value>
      <webElementGuid>edd4ebe8-a025-4171-81b0-e760d18765f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Clip</value>
      <webElementGuid>be64ec2f-7699-4817-90d9-73b4b0a6f965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-20pg7w&quot;]/main[@class=&quot;MuiBox-root css-1azpmo8&quot;]/div[@class=&quot;MuiStack-root css-nyjdb9&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-18nibrg&quot;]/div[@class=&quot;MuiStack-root css-uwa97r&quot;]/div[@class=&quot;MuiStack-root css-1orwh6x&quot;]/button[@class=&quot;css-ar65o0&quot;]</value>
      <webElementGuid>9694ec51-e344-483e-bf2c-87fabf601221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div/div[2]/button</value>
      <webElementGuid>73183207-1936-409c-b70a-10772db9b9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[9]/following::button[1]</value>
      <webElementGuid>e04c7c68-ed19-4027-b930-50901342d3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[8]/following::button[1]</value>
      <webElementGuid>0d6c611b-0d44-422d-b596-b4805ad7a45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Your Local'])[1]/preceding::button[1]</value>
      <webElementGuid>9942070f-8133-47b3-826d-bcca27a722dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>959a0d32-a0bc-4db1-86d3-dec1136387df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Get Clip' or . = 'Get Clip')]</value>
      <webElementGuid>cadfd191-1c12-4c9f-b044-58a39f250423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
