<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank youYour clip is being transcoded now. You can check it on convert to Tiktok  Reels page after 5 minutesSave templateGot it</name>
   <tag></tag>
   <elementGuidId>a9fb17b5-4cbd-47be-bdd1-2bab72eb70f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Got it!'])[1]/following::div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1da9d096-aabe-450e-a088-59b6516d4e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthXs css-h3fct8</value>
      <webElementGuid>2b3ef363-3324-4938-b18d-5bd4f205f5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>8b52e1df-c5da-45ee-ac8c-9cbeeadb1f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>alert-dialog-description</value>
      <webElementGuid>f1272c45-ff3c-4fe3-b244-b311eb78a190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>alert-dialog-title</value>
      <webElementGuid>ccbed1bc-00c8-4d4a-bf4c-af1d3014364f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank youYour clip is being transcoded now. You can check it on convert to Tiktok / Reels page after 5 minutes!Save templateGot it!</value>
      <webElementGuid>3b50f6cf-a1d2-4a4d-893c-fd3e77f39033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root MuiModal-root css-134ogvd&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthXs css-h3fct8&quot;]</value>
      <webElementGuid>c61bbe71-62bc-4613-8fb4-f944c1192302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Got it!'])[1]/following::div[6]</value>
      <webElementGuid>7976b475-fa92-46e0-808b-f8b113803dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save template'])[1]/following::div[7]</value>
      <webElementGuid>1f2a02f8-e4fe-42d3-a00e-2e6868201c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div</value>
      <webElementGuid>d3c87fda-a991-4be2-a2bb-99d738ac2b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thank youYour clip is being transcoded now. You can check it on convert to Tiktok / Reels page after 5 minutes!Save templateGot it!' or . = 'Thank youYour clip is being transcoded now. You can check it on convert to Tiktok / Reels page after 5 minutes!Save templateGot it!')]</value>
      <webElementGuid>3a9a0186-fdbb-495f-b73b-9a06d50b2f69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
