<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>preview</name>
   <tag></tag>
   <elementGuidId>c06d0fbe-5dd7-4d47-8982-6ed0d7af4504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://static-cdn.jtvnw.net/twitch-clips-thumbnails-prod/CrispyBlatantCarrotDancingBanana-RO-XQz0Gx4aH11cc/c478bd97-60ed-4325-8fca-6070a2f8a31b/preview-480x272.jpg' and @alt = 'clip-thumb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;clip-thumb&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='clip-thumb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eb6ee151-57c4-4c06-8de7-d23845ad0aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-cdn.jtvnw.net/twitch-clips-thumbnails-prod/CrispyBlatantCarrotDancingBanana-RO-XQz0Gx4aH11cc/c478bd97-60ed-4325-8fca-6070a2f8a31b/preview-480x272.jpg</value>
      <webElementGuid>f62493da-25fa-4d3c-9166-76b30011afa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>clip-thumb</value>
      <webElementGuid>7b41e5a5-5611-4219-9b48-a91c455841af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root MuiModal-root css-yh2ekv&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthLg css-168pkx9&quot;]/div[@class=&quot;MuiDialogContent-root css-i3vm3l&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-y8q14f&quot;]/div[@class=&quot;MuiBox-root css-udf0ip&quot;]/img[1]</value>
      <webElementGuid>3ee209ae-e2d4-4e5c-930a-5a83324c5773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='clip-thumb']</value>
      <webElementGuid>ce97412f-d769-4f05-b9fb-25f250e9465f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/img</value>
      <webElementGuid>0faaa4b3-40b4-4f0a-8ca5-8333af705570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static-cdn.jtvnw.net/twitch-clips-thumbnails-prod/CrispyBlatantCarrotDancingBanana-RO-XQz0Gx4aH11cc/c478bd97-60ed-4325-8fca-6070a2f8a31b/preview-480x272.jpg' and @alt = 'clip-thumb']</value>
      <webElementGuid>9fac2777-24e5-4113-b098-332ef73991f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
