<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchStreamer_Modal</name>
   <tag></tag>
   <elementGuidId>c0798bd4-c025-4871-8204-e4cb56cd7b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation24.MuiDialog-paper.MuiDialog-paperScrollPaper.MuiDialog-paperWidthLg.css-168pkx9</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Search Twitch StreamerPlease input Twitch Streamer name to start convert your clip to TikTok format​Search' or . = 'Search Twitch StreamerPlease input Twitch Streamer name to start convert your clip to TikTok format​Search')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a36ea997-0946-45fc-8de7-c8129c592bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthLg css-168pkx9</value>
      <webElementGuid>bf9be213-882d-4fa0-add3-331d8536a50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>fba68a38-0d0e-4852-8027-a1ccadac6372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>alert-dialog-description</value>
      <webElementGuid>76fa21a1-6a7c-42fd-a073-c7661f57c4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>alert-dialog-title</value>
      <webElementGuid>be1ee861-38a1-4a1a-82e4-3d29fe66be7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Twitch StreamerPlease input Twitch Streamer name to start convert your clip to TikTok format​Search</value>
      <webElementGuid>23b6b818-5c1d-4b82-a0c6-e1c6e814d834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root MuiModal-root css-yh2ekv&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthLg css-168pkx9&quot;]</value>
      <webElementGuid>ef35059c-5a7c-45b4-b495-56c3ae0ad35c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[5]</value>
      <webElementGuid>56b96f46-9bd3-4416-bb58-8a78710a39ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div</value>
      <webElementGuid>d216c543-92d7-4046-8746-8e86e413bdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Search Twitch StreamerPlease input Twitch Streamer name to start convert your clip to TikTok format​Search' or . = 'Search Twitch StreamerPlease input Twitch Streamer name to start convert your clip to TikTok format​Search')]</value>
      <webElementGuid>b9e8cf01-686d-4d4f-ae76-7065b56b6c50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
