<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Features_logo-desktop</name>
   <tag></tag>
   <elementGuidId>c831c977-81db-4648-a7ab-9494503effc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo-desktop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Eklipse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>954aab79-0093-44b4-bbc0-0f25df896aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-desktop</value>
      <webElementGuid>c2cd408a-3d9b-4cb3-89d7-39dc286a211b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/09/Eklipse-Logo_W_Updated.png?fit=251%2C54&amp;ssl=1</value>
      <webElementGuid>d9dd1eb8-3408-4d2c-ac1b-9e91e5ee1388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Eklipse</value>
      <webElementGuid>40fd1af9-f0e3-4252-855b-54cc374c4ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;home page-template-default page page-id-13271 wp-custom-logo ehf-template-eklipsegg ehf-stylesheet-eklipsegg elementor-default elementor-kit-9 elementor-page elementor-page-13271 mysticky-welcomebar-apper e--ua-blink e--ua-chrome e--ua-webkit&quot;]/header[@class=&quot;header fixed no-fixed&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main__container&quot;]/div[@class=&quot;header-main__col header-main__col--left&quot;]/div[@class=&quot;header-main__logo&quot;]/a[1]/img[@class=&quot;logo-desktop&quot;]</value>
      <webElementGuid>0ac29ef0-4822-49de-86eb-c5a1b7c34759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Eklipse']</value>
      <webElementGuid>a791e718-b142-4168-97c0-35cfefc3edc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0eca2dd0-25bd-46ad-9ee6-929d587d8104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/eklipse.gg/wp-content/uploads/2022/09/Eklipse-Logo_W_Updated.png?fit=251%2C54&amp;ssl=1' and @alt = 'Eklipse']</value>
      <webElementGuid>0e1aa974-9bcb-4560-9827-e261fad57182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
