<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_StreamVideo</name>
   <tag></tag>
   <elementGuidId>dc0877d7-8ecb-424d-b066-75713f09a650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sidebar-submenu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submenu-1']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8f051df-3ef2-43f0-b759-ff2b11cfc5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-submenu-link</value>
      <webElementGuid>fd37c0ff-8e72-4a1f-a5a2-981dd72254e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/video-library/streams</value>
      <webElementGuid>89013b52-b137-476f-b8ad-da0126c7a8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stream/Video</value>
      <webElementGuid>538bc7eb-1bcb-458e-a978-97f9982b45fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-1&quot;)/ul[1]/li[@class=&quot;stream-list-menu&quot;]/a[@class=&quot;sidebar-submenu-link&quot;]</value>
      <webElementGuid>30d5ac15-264b-4b44-9706-b5ceb8a93ec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='submenu-1']/ul/li/a</value>
      <webElementGuid>fcf26c01-9ac3-4079-a51e-ef3655afd457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clip Library'])[1]/following::a[1]</value>
      <webElementGuid>260fcff9-5432-49ad-93f9-8206d9863312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>8757f6ad-55c2-420f-a83a-eac1757e2479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitch/Kick Clips'])[1]/preceding::a[1]</value>
      <webElementGuid>429f16c5-0472-4d5d-8719-10cd47e30c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/video-library/streams')])[2]</value>
      <webElementGuid>70f66a7e-5cbf-40b9-a26d-a1741475e783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a</value>
      <webElementGuid>d8d91b33-164f-43f8-8f3c-029a4db2d09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/video-library/streams' and (text() = 'Stream/Video' or . = 'Stream/Video')]</value>
      <webElementGuid>fb3d3f6c-58b9-476f-a036-28c3d4e931d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
