<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Import Now</name>
   <tag></tag>
   <elementGuidId>9d12c48c-d6e0-4be7-89c5-456af087c71d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ek-primary-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58f2b647-b125-4830-ad99-eaa5fb66c97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3edf3c12-ce8a-4b58-afac-d24f372d9de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ek-primary-button</value>
      <webElementGuid>cf5cd0f1-34c5-4e3d-a093-8622e8bd194c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Import Now</value>
      <webElementGuid>36c5ed97-c1ae-44f2-bcee-f6493babc8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade ek-get-stream-modal w-900 modal show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;get-stream-modal-container&quot;]/div[@class=&quot;add-google-drive-stream-section upload-vod-section&quot;]/div[@class=&quot;content-right&quot;]/form[1]/div[@class=&quot;mb-3 form-group&quot;]/div[@class=&quot;text-right&quot;]/button[@class=&quot;ek-primary-button&quot;]</value>
      <webElementGuid>16c798bd-e713-407d-9839-743129e62cbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>5fd50424-6a11-43f2-b111-0acc458f6a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I confirm this is my video and authorize Eklipse.gg to process it'])[1]/following::button[1]</value>
      <webElementGuid>9d92a644-9341-460c-81bd-765a7f5bf66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please insert stream title'])[1]/following::button[1]</value>
      <webElementGuid>26c2254a-1d3e-44c7-95b9-5332f568813d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Import Now']/parent::*</value>
      <webElementGuid>696c76f6-c92e-44de-b352-4581bdada772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>e6f6cb1a-c579-4c97-baa6-7d43091c001e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Import Now' or . = 'Import Now')]</value>
      <webElementGuid>3ff2a841-6c25-4b73-bb68-82118e5e4082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
