<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConnectStreamService</name>
   <tag></tag>
   <elementGuidId>8dbe45a5-ed00-40c9-83c5-5adabab9aae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.connect-from-empty-state-section.bg-gray.py-4.px-3.border--rounded__16.h-100.d-flex.flex-column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/div/div/div[2]/div/div/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad89d813-de74-4546-9b89-bf1bc2524ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>connect-from-empty-state-section bg-gray py-4 px-3 border--rounded__16 h-100 d-flex flex-column</value>
      <webElementGuid>70141ed2-64a8-4e86-a376-73f208ebfd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76f4cb44-0b50-419d-a67c-e85be7599687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4db85559-5df8-45f2-a6a5-10f7b54e509b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connect for the Ultimate ExperienceFind your vods right after you're done streamingGet instant highlights with auto-processing</value>
      <webElementGuid>a9f4f03d-b098-4fe0-9e5b-b08f72ef989b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-streams ek-streams-page&quot;]/div[@class=&quot;ek-widget-wrapper d-flex mt-4&quot;]/div[@class=&quot;ek-content-bar&quot;]/div[@class=&quot;ek-streamlist-container d-flex flex-column flex-xl-row&quot;]/div[@class=&quot;ek-stream-list w-100&quot;]/div[@class=&quot;d-flex gap-3 mt-3 flex-column flex-md-row empty-state-for-new-user-section&quot;]/div[@class=&quot;p-3 bg-base rounded-md generate-your-stream-highlight-section w-100&quot;]/div[@class=&quot;connect-and-import-from-empty-state-section&quot;]/div[@class=&quot;connect-from-empty-state-section bg-gray py-4 px-3 border--rounded__16 h-100 d-flex flex-column&quot;]</value>
      <webElementGuid>094f8497-39cf-4610-b9b9-bd32be2bc5d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/div[2]/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>99cc49e8-fbb0-4bfb-8567-1a50e4c7d9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/following::div[5]</value>
      <webElementGuid>43f35807-6644-4a73-b69c-b1a514c04b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import'])[1]/following::div[10]</value>
      <webElementGuid>ef683475-7e79-4b7e-9c12-b968b3b48805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>73dfdee4-6c2a-4656-9243-6c9b079342d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Connect for the Ultimate ExperienceFind your vods right after you&quot; , &quot;'&quot; , &quot;re done streamingGet instant highlights with auto-processing&quot;) or . = concat(&quot;Connect for the Ultimate ExperienceFind your vods right after you&quot; , &quot;'&quot; , &quot;re done streamingGet instant highlights with auto-processing&quot;))]</value>
      <webElementGuid>09fbd9b7-9521-4dcc-bffa-f695d68b894a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
