<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExternalSource_Vod</name>
   <tag></tag>
   <elementGuidId>da9896c2-49fc-460e-860b-5d52cb13d436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.import-stream-from-empty-state-section.bg-gray.py-4.px-3.border--rounded__16.h-100.d-flex.flex-column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div/div/div/div[2]/div/div/div/div[2]/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6024e48-1d79-437f-98ab-13ae9fa6fc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>import-stream-from-empty-state-section bg-gray py-4 px-3 border--rounded__16 h-100 d-flex flex-column</value>
      <webElementGuid>97b0199d-f3aa-42d1-acf4-6f7eab272e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8dc77a5-3cd6-4511-bb10-4646cd606238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bc085611-5eca-4fb8-a7cf-61da9a3847f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate from External SourceEnter a stream URLUpload TikTok LiveUpload from local files</value>
      <webElementGuid>5fe32c04-8577-439f-b6dd-04d3cf6539d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-streams ek-streams-page&quot;]/div[@class=&quot;ek-widget-wrapper d-flex mt-4&quot;]/div[@class=&quot;ek-content-bar&quot;]/div[@class=&quot;ek-streamlist-container d-flex flex-column flex-xl-row&quot;]/div[@class=&quot;ek-stream-list w-100&quot;]/div[@class=&quot;d-flex gap-3 mt-3 flex-column flex-md-row empty-state-for-new-user-section&quot;]/div[@class=&quot;p-3 bg-base rounded-md generate-your-stream-highlight-section w-100&quot;]/div[@class=&quot;connect-and-import-from-empty-state-section&quot;]/div[@class=&quot;import-stream-from-empty-state-section bg-gray py-4 px-3 border--rounded__16 h-100 d-flex flex-column&quot;]</value>
      <webElementGuid>25b9eff7-664b-4888-b535-35b16e21bfac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/div[2]/div/div/div/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>f9cc7385-0bc1-4885-97a5-79dffa028f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::div[1]</value>
      <webElementGuid>2c98d914-da08-4ce5-9bb0-18a4cb425134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get instant highlights with auto-processing'])[1]/following::div[2]</value>
      <webElementGuid>810bf623-dab2-4e35-88ad-1ac5db0c7b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]</value>
      <webElementGuid>8a00e346-8cc5-4d3c-9293-412af54d601d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Generate from External SourceEnter a stream URLUpload TikTok LiveUpload from local files' or . = 'Generate from External SourceEnter a stream URLUpload TikTok LiveUpload from local files')]</value>
      <webElementGuid>bd4a9b73-6bd5-4db1-9f68-cd324947c6d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
