<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Video Title_formStreamTitle</name>
   <tag></tag>
   <elementGuidId>f26c2ae7-edd2-441b-9ca8-6960fbf2418c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formStreamTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formStreamTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b82078f6-ec6d-474f-b8fb-70c9ca0ecf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sample: Video Title 1</value>
      <webElementGuid>84ed9d21-4bd7-4b36-97c6-f9feda8c5d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49ca97ee-f4c9-46df-b355-30bd5f1ff4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formStreamTitle</value>
      <webElementGuid>c400d40a-163b-4769-8ffb-5312dc97774d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d85cb8dc-fa75-4604-9ec9-af1976cefe63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formStreamTitle&quot;)</value>
      <webElementGuid>a6843509-ab03-498c-87d2-1a2d77a9c7c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formStreamTitle']</value>
      <webElementGuid>0bd58dfa-5520-43c4-a4db-df24bd62db12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>1a64f354-82e8-4cc4-956c-39e4bd28e1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Sample: Video Title 1' and @type = 'text' and @id = 'formStreamTitle']</value>
      <webElementGuid>1831d531-63bc-4198-803c-f79f3e9027e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
