<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DashboardHome</name>
   <tag></tag>
   <elementGuidId>9ca98c90-1d13-403b-bf5c-ece1e26ad9f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b253629c-440f-4d7d-8c89-36442f4c12a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>2db345bf-d485-42d8-b5e9-bda2bfe196c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>☰CreateAI EditBetaEditMontageGo PremiumSaved ClipSaved ClipsConnect StatusConnection StatusConnect NowConnect NowConnect NowConnect NowConnect NowConnect NowConnect Now2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we'll turn your best moments into highlights!an hour agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogoutAI EditBetaEditMontageGo Premium2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we'll turn your best moments into highlights!an hour agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogoutImport StreamsAdd new Twitch, Tiktok, YT or Kick!AI Edit BetaEdit your clips using AI!Convert to VerticalTurn your videos into TikTok formatSharePost and Schedule your clipsPrivate StreamGame and clip privatelyDidn’t see your stream?RefreshGenerate Stream HighlightsTry with your VOD link: 3 trial availableImportSelect...Connect for the Ultimate ExperienceFind your vods right after you're done streamingGet instant highlights with auto-processingORGenerate from External SourceEnter a stream URLUpload TikTok LiveUpload from local filesPremium Exclusive Games PreviousexclusiveMonster Hunter: WildsexclusiveMarvel RivalsexclusiveCall of Duty: Black Ops 6 &amp; ZombieexclusiveOverwatch 2exclusiveValorantexclusiveClair Obscur: Expedition 33exclusiveFortniteexclusiveFragPunkexclusiveCOD: Warzone3-2exclusiveOff The GridSee more NextCommunity HighlightsWeekly Best Clipswill felicianoFortnite·Cory shookCOD: Warzone3-2·Single killSneakerb0ssCOD: Warzone3-2·Wanma95Other Games·emotional-momentTutorialCreate a Montage ClipAI EditConvert to TiktokHow to Use Eklipse Website 101How to Import Kick StreamsHow to Import/ UploadContent PublisherVoice CommandSee moreEnable desktop notifications for app.eklipse.ggOKNot Now</value>
      <webElementGuid>b391d69c-ec74-4a5c-8d80-673beece3c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]</value>
      <webElementGuid>581d4bca-1f1f-4863-87dd-5499eaad57f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div</value>
      <webElementGuid>2d68a736-ac15-4934-a622-dd02a9151ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Japanese'])[1]/following::div[2]</value>
      <webElementGuid>cc6eaa93-8f64-45ea-8ce1-38628958b416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='French'])[1]/following::div[2]</value>
      <webElementGuid>2857ef05-db4b-4224-bfb5-9c08fb1696ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>19d9f874-aa80-4d95-9844-294eedea775d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;☰CreateAI EditBetaEditMontageGo PremiumSaved ClipSaved ClipsConnect StatusConnection StatusConnect NowConnect NowConnect NowConnect NowConnect NowConnect NowConnect Now2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we&quot; , &quot;'&quot; , &quot;ll turn your best moments into highlights!an hour agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogoutAI EditBetaEditMontageGo Premium2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we&quot; , &quot;'&quot; , &quot;ll turn your best moments into highlights!an hour agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogoutImport StreamsAdd new Twitch, Tiktok, YT or Kick!AI Edit BetaEdit your clips using AI!Convert to VerticalTurn your videos into TikTok formatSharePost and Schedule your clipsPrivate StreamGame and clip privatelyDidn’t see your stream?RefreshGenerate Stream HighlightsTry with your VOD link: 3 trial availableImportSelect...Connect for the Ultimate ExperienceFind your vods right after you&quot; , &quot;'&quot; , &quot;re done streamingGet instant highlights with auto-processingORGenerate from External SourceEnter a stream URLUpload TikTok LiveUpload from local filesPremium Exclusive Games PreviousexclusiveMonster Hunter: WildsexclusiveMarvel RivalsexclusiveCall of Duty: Black Ops 6 &amp; ZombieexclusiveOverwatch 2exclusiveValorantexclusiveClair Obscur: Expedition 33exclusiveFortniteexclusiveFragPunkexclusiveCOD: Warzone3-2exclusiveOff The GridSee more NextCommunity HighlightsWeekly Best Clipswill felicianoFortnite·Cory shookCOD: Warzone3-2·Single killSneakerb0ssCOD: Warzone3-2·Wanma95Other Games·emotional-momentTutorialCreate a Montage ClipAI EditConvert to TiktokHow to Use Eklipse Website 101How to Import Kick StreamsHow to Import/ UploadContent PublisherVoice CommandSee moreEnable desktop notifications for app.eklipse.ggOKNot Now&quot;) or . = concat(&quot;☰CreateAI EditBetaEditMontageGo PremiumSaved ClipSaved ClipsConnect StatusConnection StatusConnect NowConnect NowConnect NowConnect NowConnect NowConnect NowConnect Now2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we&quot; , &quot;'&quot; , &quot;ll turn your best moments into highlights!an hour agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogoutAI EditBetaEditMontageGo Premium2NotificationNotificationActivities (1)Updates (1)Reminder[Important] Connect your stream account now!Click here to pick your streaming accounts &amp; we&quot; , &quot;'&quot; , &quot;ll turn your best moments into highlights!an hour agoSee AllProfileArczyeddafashafi@gmail.comUpgrade to PremiumLanguageLanguageEnglishSpanishGermanFrenchJapaneseWorkspaceAccount SettingsHelpLogoutImport StreamsAdd new Twitch, Tiktok, YT or Kick!AI Edit BetaEdit your clips using AI!Convert to VerticalTurn your videos into TikTok formatSharePost and Schedule your clipsPrivate StreamGame and clip privatelyDidn’t see your stream?RefreshGenerate Stream HighlightsTry with your VOD link: 3 trial availableImportSelect...Connect for the Ultimate ExperienceFind your vods right after you&quot; , &quot;'&quot; , &quot;re done streamingGet instant highlights with auto-processingORGenerate from External SourceEnter a stream URLUpload TikTok LiveUpload from local filesPremium Exclusive Games PreviousexclusiveMonster Hunter: WildsexclusiveMarvel RivalsexclusiveCall of Duty: Black Ops 6 &amp; ZombieexclusiveOverwatch 2exclusiveValorantexclusiveClair Obscur: Expedition 33exclusiveFortniteexclusiveFragPunkexclusiveCOD: Warzone3-2exclusiveOff The GridSee more NextCommunity HighlightsWeekly Best Clipswill felicianoFortnite·Cory shookCOD: Warzone3-2·Single killSneakerb0ssCOD: Warzone3-2·Wanma95Other Games·emotional-momentTutorialCreate a Montage ClipAI EditConvert to TiktokHow to Use Eklipse Website 101How to Import Kick StreamsHow to Import/ UploadContent PublisherVoice CommandSee moreEnable desktop notifications for app.eklipse.ggOKNot Now&quot;))]</value>
      <webElementGuid>faa1cb03-41c3-4414-8bdb-ff74261e3c8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
