<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Preview</name>
   <tag></tag>
   <elementGuidId>df1f4f19-8f67-465f-a39f-06aab4455e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[105]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a6dfbeb-fefc-4ead-bd4c-40fed7d063b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26596c30-888f-42e3-9e3f-99d012dbec07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-preview d-flex justify-content-center align-items-center</value>
      <webElementGuid>3dbe3b73-a946-4d71-9cd2-fe3c2a03c4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>e8d55c35-b3d3-4795-8d90-e808799a37c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;focus-outline-hidden&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade ai-edit-modal-container current-step-2 modal show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;ai-edit-modal-container&quot;]/div[1]/div[@class=&quot;choose-ai-edit-panel&quot;]/div[2]/div[@class=&quot;ek-demo-clips-ai-edit&quot;]/div[@class=&quot;clip-slider-container&quot;]/div[@class=&quot;slick-slider clip-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@id=&quot;https://dxcikqk9k66cl.cloudfront.net/1217738973_2024-07-15_12:25:59.mp4&quot;]/div[@class=&quot;video-container d-flex justify-content-center align-items-center&quot;]/div[@class=&quot;btn-container flex-column w-100 align-items-center&quot;]/button[@class=&quot;btn-preview d-flex justify-content-center align-items-center&quot;]</value>
      <webElementGuid>583cf0b1-6e51-4cdc-af7a-8ed62ac6ebd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[105]</value>
      <webElementGuid>ed9879bb-fa39-41fa-8665-7604e58a4636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='https://dxcikqk9k66cl.cloudfront.net/1217738973_2024-07-15_12:25:59.mp4']/div/div/button[2])[3]</value>
      <webElementGuid>1bbae0d9-df55-4f0e-9363-31625ae55921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[26]/following::button[1]</value>
      <webElementGuid>78839655-a033-4aa7-8937-f47818149888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bb'])[3]/preceding::button[1]</value>
      <webElementGuid>d99a05ce-4f37-4119-83b4-c52f774e2bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div[4]/div/div/div/div/button[2]</value>
      <webElementGuid>a89622a1-72ff-49d4-88f6-eb1a02435fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Preview' or . = 'Preview')]</value>
      <webElementGuid>f7cbb9d2-6da4-4605-9ee0-35e7d913f4bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
