<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConnectToKick</name>
   <tag></tag>
   <elementGuidId>5d93dc0c-a1d6-4528-8dc7-5608c4ca7a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swal2-html-container']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.example-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acf91577-f8de-4d24-9021-00f58c4980cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>example-block</value>
      <webElementGuid>0fa4b62e-22aa-4784-8668-59e5938125f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> kick.com/channelname/clips/clip_id</value>
      <webElementGuid>f4b24f87-a58c-46bc-8ed8-41cc90f1420f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-html-container&quot;)/div[@class=&quot;invalid-url-modal&quot;]/div[2]/div[@class=&quot;example-block&quot;]</value>
      <webElementGuid>962f7739-6260-4e6b-8b88-a140da0d5a57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swal2-html-container']/div/div[2]/div</value>
      <webElementGuid>68706a90-c195-48a8-8013-5250514bc7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please input the valid clip URL.These are the examples of a valid URL'])[1]/following::div[2]</value>
      <webElementGuid>3efeb917-3753-4ae4-8c0a-3658fb25757b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Url'])[1]/following::div[5]</value>
      <webElementGuid>e048b350-1e51-4bce-a1ad-ff9a1b851720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Understood'])[1]/preceding::div[6]</value>
      <webElementGuid>048f7404-cf5f-4646-bc49-ef9672e9617f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='kick.com/channelname/clips/clip_id']/parent::*</value>
      <webElementGuid>2a743dfb-4cd2-48be-99e1-ab108f28c6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>c77dfdc2-74b4-4a05-99c1-73b76250f67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' kick.com/channelname/clips/clip_id' or . = ' kick.com/channelname/clips/clip_id')]</value>
      <webElementGuid>101ab355-2bcb-477e-ab7c-e8995c64ce37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
