<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home_Submenu</name>
   <tag></tag>
   <elementGuidId>1559f5c8-0368-4c66-bffd-16e03f81f3d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='icon-toggle-sub-menu-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon-toggle-sub-menu-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1a73e40f-01e0-4941-95c9-c1112b6e84ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-toggle-sub-menu-2</value>
      <webElementGuid>a6932db5-e6c5-4c77-a51f-9e94ccbea9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-down-chevron</value>
      <webElementGuid>9b7191b9-2c05-40b8-9b20-d999f5ec44d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-toggle-sub-menu-2&quot;)</value>
      <webElementGuid>779f66d5-ee6b-4b6e-81f6-d6b42a13c40f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='icon-toggle-sub-menu-2']</value>
      <webElementGuid>ae5a2c1c-46cf-4a5f-9c51-7fe918008a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mySidebar']/div[2]/nav/ul/li[6]/span/i</value>
      <webElementGuid>53c7d6a5-58b7-4df8-be8f-5caadff55e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span/i</value>
      <webElementGuid>98434385-06bf-47e2-885b-cc885c0ae112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'icon-toggle-sub-menu-2']</value>
      <webElementGuid>c910e37e-cc20-4229-93cc-a1ad1ab18acd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
