<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>92190f9f-3bbd-4b35-aa55-038f07326325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='https://dxcikqk9k66cl.cloudfront.net/1462034287_2024-07-15_12:26:55.mp4']/div/video)[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>4e1199e9-acd1-4971-94b5-01d5465fc99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dxcikqk9k66cl.cloudfront.net/1462034287_2024-07-15_12:26:55.mp4</value>
      <webElementGuid>25c14191-ff76-44d7-93f5-710f40c12531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;focus-outline-hidden&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade ai-edit-modal-container current-step-2 modal show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;ai-edit-modal-container&quot;]/div[1]/div[@class=&quot;choose-ai-edit-panel&quot;]/div[2]/div[@class=&quot;ek-demo-clips-ai-edit&quot;]/div[@class=&quot;clip-slider-container&quot;]/div[@class=&quot;slick-slider clip-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@id=&quot;https://dxcikqk9k66cl.cloudfront.net/1462034287_2024-07-15_12:26:55.mp4&quot;]/div[@class=&quot;video-container d-flex justify-content-center align-items-center&quot;]/video[1]</value>
      <webElementGuid>7386db84-8d26-4ef2-afa1-a1d4e038c47b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='https://dxcikqk9k66cl.cloudfront.net/1462034287_2024-07-15_12:26:55.mp4']/div/video)[3]</value>
      <webElementGuid>55262f0e-c814-47c4-8aa8-2f9670e539bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div[7]/div/div/div/video</value>
      <webElementGuid>fedc6d40-5745-4a2b-b2eb-0d756552ea1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'https://dxcikqk9k66cl.cloudfront.net/1462034287_2024-07-15_12:26:55.mp4']</value>
      <webElementGuid>be64964c-10c3-4026-beeb-cfacfeade134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
