<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Valorant_clip-thumbnail</name>
   <tag></tag>
   <elementGuidId>8521783e-3264-49a6-96be-f29f82bcdbb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='clip-thumb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.clip-thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e214d8e1-8699-4a51-a2f2-87092fd8eba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clip-thumbnail</value>
      <webElementGuid>3a37330e-5f19-4f67-a6a5-0db09c57d99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-cdn.jtvnw.net/twitch-clips-thumbnails-prod/CrispyBlatantCarrotDancingBanana-RO-XQz0Gx4aH11cc/c478bd97-60ed-4325-8fca-6070a2f8a31b/preview-480x272.jpg</value>
      <webElementGuid>fd7ad637-876b-4eb7-b8f0-9b6d696302ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>clip-thumb</value>
      <webElementGuid>21492e0a-f326-4442-b9fa-5556bde281ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade ek-search-twitch-channel modal show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;clips-container&quot;]/div[@class=&quot;list-clips&quot;]/div[@class=&quot;clip-preview&quot;]/img[@class=&quot;clip-thumbnail&quot;]</value>
      <webElementGuid>d1ce9045-02f2-473e-a532-ab42f9dfa109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='clip-thumb']</value>
      <webElementGuid>34cd3e16-93ea-4c1e-8ab4-9776c79c2ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/img</value>
      <webElementGuid>a8085dd9-0677-4a62-8244-861b00c37dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static-cdn.jtvnw.net/twitch-clips-thumbnails-prod/CrispyBlatantCarrotDancingBanana-RO-XQz0Gx4aH11cc/c478bd97-60ed-4325-8fca-6070a2f8a31b/preview-480x272.jpg' and @alt = 'clip-thumb']</value>
      <webElementGuid>584ef09a-a120-4f9f-b79e-b0fa90f7f1dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
