<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>0850213e-4e7c-4794-b6ca-b7eaa1ba559e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='https://dxcikqk9k66cl.cloudfront.net/1217738973_2024-07-15_12:25:59.mp4']/div/video</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>4a2f574c-8015-49b6-8c1e-18aaec5a079c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dxcikqk9k66cl.cloudfront.net/1217738973_2024-07-15_12:25:59.mp4</value>
      <webElementGuid>a7cb012b-babc-473a-b2f2-fa54ea6e5b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;focus-outline-hidden&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade ai-edit-modal-container current-step-2 modal show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;ai-edit-modal-container&quot;]/div[1]/div[@class=&quot;choose-ai-edit-panel&quot;]/div[2]/div[@class=&quot;ek-demo-clips-ai-edit&quot;]/div[@class=&quot;clip-slider-container&quot;]/div[@class=&quot;slick-slider clip-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@id=&quot;https://dxcikqk9k66cl.cloudfront.net/1217738973_2024-07-15_12:25:59.mp4&quot;]/div[@class=&quot;video-container d-flex justify-content-center align-items-center&quot;]/video[1]</value>
      <webElementGuid>30f030b0-6bc0-4ae1-b377-6447ea420405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='https://dxcikqk9k66cl.cloudfront.net/1217738973_2024-07-15_12:25:59.mp4']/div/video</value>
      <webElementGuid>c77a1b7a-8264-4713-bc27-f84507b8a5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/video</value>
      <webElementGuid>ba26ed1c-efb0-4f32-ad04-58e965c42b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'https://dxcikqk9k66cl.cloudfront.net/1217738973_2024-07-15_12:25:59.mp4']</value>
      <webElementGuid>26da8f34-9de3-46f6-867d-388412a9862b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
