<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Editsubmenu</name>
   <tag></tag>
   <elementGuidId>f1ff6bf8-47ce-4b0e-9f13-9744fe0d727e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icon-toggle-sub-menu-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='icon-toggle-sub-menu-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>97d40bbf-9bf7-4fdf-8a00-ddcf7cac962d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-toggle-sub-menu-2</value>
      <webElementGuid>6f7ad3b0-98bd-4869-bb23-59168228625a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-up-chevron</value>
      <webElementGuid>b1a3f31d-e2d8-4656-a50d-9a5f66f7a988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-toggle-sub-menu-2&quot;)</value>
      <webElementGuid>69c0bcd1-b5ee-4121-8966-62efa71bf4d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='icon-toggle-sub-menu-2']</value>
      <webElementGuid>01935cf3-c41a-4a60-a587-ab1b42863280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mySidebar']/div[2]/nav/ul/li[6]/span/i</value>
      <webElementGuid>2ee1b682-9792-4f7b-87ef-30cbdc05d494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span/i</value>
      <webElementGuid>f4429f12-35ea-492e-8639-a4e517f8f0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'icon-toggle-sub-menu-2']</value>
      <webElementGuid>56be9a70-7f0d-44d9-8778-4972d313d452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
